### ISSUE TITLE
Add OpenStack Swift support

### ISSUE THREAD

**Issue by swill** [nickoneill/hugomac#5]
I would be interested in adding support for OpenStack Swift as an object storage endpoint.  I do not have experience with swift (as a programming language), but I am pretty confident in my ability to learn what I need to.  Do you have suggestions for how we can make the endpoints pluggable so I can just write a plugin for adding an additional storage endpoint?

I have tested and validated the ability to use OpenStack Swift as hosting provider for Hugo sites.  I was about to build functionality similar to yours when I found this project and thought it may just make sense for me to contribute Swift here instead of building my own tool from scratch...

**Comment by nickoneill** [comment]
Hey @swill, this would be awesome. I would definitely like to extend this for other providers.

I would start by replacing the `transferToS3` function with a `transferToOpenStack` function that implements the openstack upload API. You can see the S3 version just iterates through the publish directory and uploads everything available. If OpenStack has an Objective-C or Swift SDK (preferably a cocoapod), this will make your work much easier!

If you can accomplish this, I'll work on the code and UI for selecting different hosting providers. Sound fair?

**Comment by swill** [comment]
That sounds good.  I will check to see what SDKs are available for Swift.  I have worked with it mainly in Golang and Python, so I will see what my options are for compatible libs.

**Comment by swill** [comment]
@nickoneill It does not look like there are any native SDKs for OpenStack Swift for Objective-C or Swift (apple).  I will have to figure out what my options are then.  I could potentially just write my own implementation of an API wrapper for OpenStack Swift (I have done similar previously), but since I would be learning swift (apple) to do it, I will admit I am not a huge fan of this option.  :P

https://wiki.openstack.org/wiki/SDKs

**Comment by nickoneill** [comment]
Yeah, it looks like that's going to be the case. Happy to help you along the way if you still want to tackle it, Swift is a lot of fun to write once you get going with it. I find that I'm really productive in it, similar to how I feel about golang.

**Comment by swill** [comment]
Honestly, this is a side project for me and it is not directly in my path to success, so I will probably hold off building this for now.  Sorry for the inconvenience and false start here.  I think I am going to just write a small client in Golang since I have all the OpenStack Swift stuff working already in Golang.  Feel free to close this issue.  :)

**Comment by nickoneill** [comment]
No problem!
