### ISSUE TITLE
pod install fails

### ISSUE THREAD

**Issue by paulwakeford** [nickoneill/hugomac#6]
$ pod install
Updating local specs repositories
Analyzing dependencies
Pre-downloading: `AWSCore` from `git@github.com:nickoneill/aws-sdk-osx.git`, commit `52576e4`

[!] Error installing AWSCore
[!] /usr/bin/git clone git@github.com:nickoneill/aws-sdk-osx.git /var/folders/9g/tzy_m7l93jl2vwd1v6s3mgj15zbzs_/T/d20151119-34569-1yyegxe

Cloning into '/var/folders/9g/tzy_m7l93jl2vwd1v6s3mgj15zbzs_/T/d20151119-34569-1yyegxe'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Current Yosemite, XCode 7.

Thanks,

Paul

**Comment by nickoneill** [comment]
Hey @paulwakeford, this version of AWSCore is just a public fork on github here: https://github.com/nickoneill/aws-sdk-osx

Do you have trouble cloning it separately? If not, you can always download it and tell pod where it lives locally. I suspect this was a transient github issue though, hopefully another try will work.

**Comment by paulwakeford** [comment]
It cloned OK via the OSX GitHub UI which provided a clue - it turned out Github had helpfully disabled all my SSH keys for inactivity. Once fixed - all good. Thanks.
